DROP TABLE IF EXISTS stories
CASCADE;

CREATE TABLE stories
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  title VARCHAR(255) NOT NULL,
  picture_url VARCHAR(255),
  is_completed BOOLEAN DEFAULT FALSE
);
